# AI-Powered Data Quality Monitor Configuration

database:
  type: "duckdb"
  path: "data/dqm_database.db"
  
anomaly_detection:
  isolation_forest:
    contamination: 0.1
    n_estimators: 100
    random_state: 42
  
  dbscan:
    eps: 0.5
    min_samples: 5
  
  thresholds:
    high_anomaly_score: 0.8
    medium_anomaly_score: 0.5

data_quality:
  metrics:
    - completeness
    - uniqueness
    - validity
    - consistency
    - timeliness
  
  thresholds:
    excellent: 0.95
    good: 0.80
    fair: 0.60
    poor: 0.0

dashboard:
  title: "AI-Powered Data Quality Monitor"
  theme: "light"
  auto_refresh: true
  refresh_interval: 30  # seconds

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 